### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by akutuzov** [dmitriigriffin/dmitriigriffin.github.io#3]
В футере предлагаю:

1. ссылки "Home" и "Features" убрать (всё равно не ведут никуда)
2. вместо "© 2022 Smårådina" поставить свободную лицензию типа CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/) - если мы вообще хотим как-то указывать копирайт

**Comment by dmitriigriffin** [comment]
сделано, оставил ссылку на Смородину, но поменял концепт
