### ISSUE TITLE
Карточки об альтернативной службе для призывников

### ISSUE THREAD

**Issue by smaaraadina** [dmitriigriffin/dmitriigriffin.github.io#5]
Надо добавить карточки отсюда https://www.instagram.com/p/CbAkIphMhmH на страницу "Мобилизуйте матерей" - раздел "Матерям срочников и призывников". Там уже довольно много информации, думаю, как ее лучше упорядочить... Можно ли сделать "карусель" с карточками, как в инстаграме?

**Comment by dmitriigriffin** [comment]
Мне кажется, делать карусель во всплывашках - слегка порочная практика. Я думаю, что данная информация подходит больше в раздел "не воюйте", и там не так уж и много текста.

**Comment by smaaraadina** [comment]
В "не воюйте" тоже подходит, да. Я бы добавила в оба.

**Comment by dmitriigriffin** [comment]
готово
